version: 2

default: &defaults
  working_directory: ~/repo
  steps:
    - checkout
    - run: cask
    - run: cask install
    - run:
        name: test
        command: sh run-tests.sh

jobs:
  "emacs-24":
    docker:
      - image: silex/emacs:24-dev
    <<: *defaults
  "emacs-25":
    docker:
      - image: silex/emacs:25-dev
    <<: *defaults
  "emacs-26":
    docker:
      - image: silex/emacs:26-dev
    <<: *defaults

workflows:
  version: 2
  build:
    jobs:
      - "emacs-24"
      - "emacs-25"
      - "emacs-26"
