version: 2
jobs:
  build:
    docker:
      - image: iquiw/emacs-circleci:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: test
          command: emacs -l properties-mode.el -l properties-mode-tests.el --batch -f ert-run-tests-batch
