version: 2
jobs:
  build:
    docker:
      - image: iquiw/emacs-circleci:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: cask
      - run: cask install
      - run:
          name: test
          command: cask emacs -Q -L . -l properties-mode-tests.el --batch -f ert-run-tests-batch-and-exit
          environment:
            UNDERCOVER_FORCE: 1
