version: 2
jobs:
  build:
    docker:
      - image: iquiw/emacs-circleci:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: cask
      - run: cask install
      - run:
          name: test
          command: sh run-tests.sh
